"""empty message

Revision ID: 0f3d062473a6
Revises: 4ab099fd64be
Create Date: 2023-09-13 17:03:29.224151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f3d062473a6'
down_revision = '4ab099fd64be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('follows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('follower', sa.INTEGER(), nullable=False),
    sa.Column('followed', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['followed'], ['users.id'], name='fk_follows_followed_users'),
    sa.ForeignKeyConstraint(['follower'], ['users.id'], name='fk_follows_follower_users'),
    sa.PrimaryKeyConstraint('follower', 'followed', name='pk_follows')
    )
    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.VARCHAR(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='fk_comments_post_id_posts'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_comments_user_id_users'),
    sa.PrimaryKeyConstraint('post_id', 'user_id', name='pk_comments')
    )
    # ### end Alembic commands ###
