"""rename secondary for likes

Revision ID: be027e600bf1
Revises: 0f3d062473a6
Create Date: 2023-11-08 19:28:02.574155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be027e600bf1'
down_revision = '0f3d062473a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_user_likes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_user_likes_post_id_posts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_post_user_likes_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'post_id', name=op.f('pk_post_user_likes'))
    )
    op.drop_table('user_likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_likes',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='fk_user_likes_post_id_posts'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_likes_user_id_users'),
    sa.PrimaryKeyConstraint('user_id', 'post_id', name='pk_user_likes')
    )
    op.drop_table('post_user_likes')
    # ### end Alembic commands ###
