"""empty message

Revision ID: be3986235036
Revises: d59c4b601867
Create Date: 2023-06-26 19:10:25.025607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be3986235036'
down_revision = 'd59c4b601867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_likes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_likes_user_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_user_likes_post_id_posts', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_likes_post_id_posts'), 'posts', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_user_likes_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_likes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_likes_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_user_likes_post_id_posts'), type_='foreignkey')
        batch_op.create_foreign_key('fk_user_likes_post_id_posts', 'posts', ['post_id'], ['id'])
        batch_op.create_foreign_key('fk_user_likes_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
